Repository itda-ieoso/itda-ieoso_frontend, pull requests merged in 2025-05, with the labels that each got.

#163 fix: 관리 페이지 API 중복 호출 수정
  src/component/api/classApi.js
  src/component/page/Class.jsx
  src/component/page/class/Admin.jsx
  src/component/page/class/admin/Setting.jsx
  src/component/ui/class/AdminTopBar.jsx
  src/component/ui/class/ClassTopbar.jsx
Labels: 예빈, fix

#165 DESIGN: 페이지 간 여백 통일
  src/component/page/ClassList.jsx
  src/component/page/class/Create.jsx
  src/component/page/class/Notice.jsx
  src/component/page/dashboard/Dashboard.jsx
  src/component/page/dashboard/Sidebar.jsx
  src/component/page/dashboard/TaskList.jsx
  src/component/page/dashboard/WeekCalendar.jsx
  src/component/page/users/UsersInfoContainer.jsx
  src/component/ui/TopBar.jsx
  src/component/ui/class/AdminTopBar.jsx
  src/component/ui/class/ClassLayout.jsx
Labels: 예빈, design

#195 feat: 과제 보기 페이지 구현
  src/App.jsx
  src/component/api/classCurriculumApi.js
  src/component/img/icon/leftbutton.svg
  src/component/img/icon/rightbutton.svg
  src/component/page/class/AssignmentBrowse.jsx
  src/component/page/class/AssignmentSubmit.jsx
  src/component/page/class/Playing.jsx
  src/component/ui/class/AssignmentBrowseSidebar.jsx
  src/component/ui/class/AssignmentSubmitSidebar.jsx
  src/component/ui/class/ClassTopbar.jsx
  src/component/ui/class/PlayingCurriculumSidebar.jsx
Labels: enhancement

#193 FIX: 여러 에러 수정
  src/App.jsx
  src/component/api/api.js
  src/component/api/tokenManager.js
  src/component/page/ClassList.jsx
  src/component/page/users/LogIn.jsx
  src/component/page/users/UsersInfoContainer.jsx
  src/component/ui/TopBar.jsx
  src/utils/collectVisibleTexts.js
Labels: fix
